export default {
  pages: {
    key: "title",
    data: [
      {title: "数据可视化",            url: "/home/datavisualization",      icon: "LayoutIcon",     is_bookmarked: false},
      {title: "组合标签",            url: "/labelserach/ApexCharts",      icon: "LayoutIcon",     is_bookmarked: false},
      {title: "标签筛选",            url: "/labelserach/labelserach",      icon: "LayoutIcon",     is_bookmarked: false},
      {title: "个人画像",            url: "/charts-and-maps/charts/chartjs",      icon: "LayoutIcon",     is_bookmarked: false},
      {title: "群体画像",            url: "/charts-and-maps/charts/echarts",      icon: "LayoutIcon",     is_bookmarked: false},

      {title: "标签详情 - 人口属性",        url: "/home/Label/genderList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 商业属性",        url: "/home/Label2/consCycleList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 行为属性",        url: "/home/Label3/recentLoginList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 用户属性",        url: "/home/Label4/realEstateList",      icon: "ListIcon",     is_bookmarked: false},

      {title: "标签详情 - 性别",            url: "/home/Label/genderList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 年龄段",          url: "/home/Label/ageList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 身高",            url: "/home/Label/heightList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 民族",            url: "/home/Label/nationList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 籍贯",          url: "/home/Label/hometownList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 政治面貌",          url: "/home/Label/politicList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 职业",          url: "/home/Label/jobList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 婚姻状况",          url: "/home/Label/marriageList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 学历",          url: "/home/Label/educationList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 就业状况",          url: "/home/Label/employmentList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 星座",          url: "/home/Label/constellationList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 所在商圈",          url: "/home/Label/businessDistrictList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 国籍",          url: "/home/Label/countryList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 消费周期",          url: "/home/Label2/consCycleList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 消费能力",          url: "/home/Label2/consPowerList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 客单价",          url: "/home/Label2/unitPriceList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 支付方式",          url: "/home/Label2/payMethodList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 单笔最高",          url: "/home/Label2/singleHighestList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 购买频率",          url: "/home/Label2/purchaseFreqList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 退货率",          url: "/home/Label2/returnRateList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 换货率",          url: "/home/Label2/exchangeRateList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 省钱能手",          url: "/home/Label2/moneySaverList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 有券必买",          url: "/home/Label2/couponList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 客服咨询频率",          url: "/home/Label2/consultFreqList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 最近登录",          url: "/home/Label3/recentLoginList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 浏览页面",          url: "/home/Label3/pageBrowsedList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 浏览时长",          url: "/home/Label3/timeBrowsedList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 访问频率",          url: "/home/Label3/visitFreqList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 设备类型",          url: "/home/Label3/equipmentList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 浏览时段",          url: "/home/Label3/browsePeriodList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 登录频率",          url: "/home/Label3/loginFreqList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 品类偏好",          url: "/home/Label3/preferredCategoryList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 品牌偏好",          url: "/home/Label3/preferredBrandList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 房产",          url: "/home/Label4/realEstateList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 房产价值",          url: "/home/Label4/propertyValueList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 车产",          url: "/home/Label4/carProdList",      icon: "ListIcon",     is_bookmarked: false},
      {title: "标签详情 - 车产价值",          url: "/home/Label4/carValueList",      icon: "ListIcon",     is_bookmarked: false},

    ]
  }
}
